name: firebase_getx_boilerplate
description: firebase_getx_boilerplate Project

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Model View Controller Plugin
  get: ^4.6.5

  # Local Database
  shared_preferences: ^2.0.15
  get_storage: ^2.0.3   
  hive: ^2.2.3

  # Image File
  flutter_svg: ^1.1.1+1
  lottie: ^1.3.0

  # Security
  crypto: ^3.0.2

  # Json
  json_serializable: ^6.3.0
  build_runner: ^2.1.11

  # Lints
  flutter_lints: ^2.0.1

  # Ready to Build App
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.9.3

  # 
  google_sign_in: ^5.4.0

  # HTTP
  dio: ^4.0.6
  jwt_decoder: ^2.0.1

  # Native Widget
  fluttertoast: ^8.0.9
  
  # Good Widget
  shimmer: ^2.0.0
  flutter_keyboard_visibility: ^5.3.0

  # Util
  intl: ^0.17.0
  uuid: ^3.0.6
  permission_handler: ^10.0.2
  flutter_secure_storage: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.ttf
          weight: 900
